= Evaluating Type-Driven Development
:sectnums:
:toc:


== Purpose 

The purpose of this document is to describe, define, and evaluate the feasibility of type-driven development for the project. This is to ensure that the project artifacts such as source code are developed in a professional, organized, and well thought-of manner. The ability to develop and deploy clean, readable, and maintainable code is a skill that must be develop in order to excel at software engineering.

== Scope

The scope of this evaluation is all of the source code that is created.

== Definitions

=== What is Type-Driven Development?

It is a programming style, where the types are developed first, and then methods are extracted from those types. However, it does not end there, proving the correctness of the code is important, and is done with the compiler.

An important step in type driven development is to define domain states. In the domain of Cafeteria Ordering, states like `is_signedIn`, `Ordering`, and `Paying` prevent bugs that could be caused by the overlap of unrelated actions like paying without ordering. These states, along with abstract algebraic data types like `user` aid in the development of clean and testable code.

One important thing to mention is that type-driven development is associated with functional programming languages such as Idris, but most of these concepts can be applied to typed languages such as typescript, c++, or rust.

==== Examples of Type-Driven development

Examples provided by `Wim Jongeneel`, see reference [1].

Example of unclear typing, causing confusion of which state is the application in.
[source, Typescript]
----
interface OverviewState {
  items: Blog[]
  loading: boolean
  error?: Error
}

const ExampleState: OverviewState = {
  items: [
    {title: 'Lorem ipsum'}, 
    {title: 'Lorem ipsum'}
  ],
  loading: true,
  error: new Error('failed to parse data')
}
----

Example where state is clear.

[source, Typescript]
----
interface OverviewState {
  items:  
    | "loading" 
    | Blog[]
    | Error
}
----

Here we can see that we are either loading, showing the content, or an error occurred, which is easier to debug and test.

== Usage

=== How can Type-Driven Development be applied in Cafeteria Ordering?

==== Examples within the app

== Conclusion

== References


