= Defect Management and Defect severity classification guidelines
:toc:

== Overview

The purpose of this document is for the team to have a guideline to follow when encountering bugs, it is preferred to encounter defects as soon as possible during the lifetime of the project. This section depends on risk evaluation of any features presented and added to the project; specifically defect severity is very strongly associated with risk assessment of any given feature. Severity in this document will be presented independently of risks but will attach priority values as examples.

== Defect Management Process step-by-step

Defect Management is the process with which defects / bugs are handled. The defect / bug lifecycle is a part of defect management, but they are not the same.  

Once a defect has been detected through various testing activities such as unit testing, integration testing, system testing, and user acceptance testing. Follow the steps bellow:

* *Defect identification / New bug found*
** Defect is identified by either automated testing, manual testing or user acceptance testing footnote:[User acceptance testing refers to a user trying the software after going through defect management process prior to a release, in this project's case it can be at after testing and completing a feature] 

* *Defect logging*
** Tester logs the defect with detailed information description, steps to reproduce and add to defect tracking log. Should be accessible by at least all testers. Recommended to use github discussions to eventually create an issue that resolves the defect.

* *Defect triage*
** Assign severity and priority values to defect in tracking log.

* *Defect assignment*
** Assign a developer to fix the defect encountered

* *Defect resolution*
** Developer fixes the defect

* *Defect verification*
** Retest to verify defect is resolved footnote:[Retesting and regression testing strategy and policy not covered in this document]

* *Defect closure*
** Defect has been verified as resolved, update status of defect in tracking

* *Defect reporting*
** The second most important step after defect tracking, is to report weekly, the number of defects open, resolved, and the average amount of time it takes to fix defect. This would likely be done by a Team Lead.

== Defect Priority
Defect priority can also be referred to as urgency to fix an encountered defect. It works hand in hand with severity and risks to decide order in which defects should be fixed. Priority for them should be classified using the following table.
[cols="1,3"]
|===
| High  | Needs to be fixed immediately, often associated with a critical or Blocker level of severity defect.
| Medium | Defects that should be fixed next Milestones. In case of Milestone 3 they should be a focus along with High priority defects.
| Low | Defects that don't affect the function of the system, often details in UI, grammar that can be fixed later.
|===
== Defect Severity Classification
Defect Severity is also referred to as defect impact. It works together with defect priority to establish the order to fix encountered problems in the systems.
[cols="1,3"]
|===
| *Severity* | *Definition*
| Blocker | prevents system from starting/running
| Critical | prevents a feature from working correctly, has workaround
| Major | defect impacts the feature but does not prevent core functionality of the feature
| Minor | minimal impact defect that affects a small component of the feature
| Trivial | defect has almost no impact on feature or system
|===

== Severity and priority example ordering

When deciding what defects to fix first, Blocker defects always go before any other and they are always classified as High Priority. Since trivial has almost no impact on feature, it can be left or packaged with another defect fix that relates to it. There can be some cases where a defect encountered poses a low severity but really high priority, for example a typo in product name. These types of issues are often very important a business perspective and would likely be a priority despite of how easy it is to fix.

[cols="4*"]
|===
| *Order* | *Priority* | *Severity*  | *Example*
| 1st | High | Critical | order made does not show up for employees. very likely to occur
| 2nd | Medium | Critical | a defect that can likely occur during regular use
| 3rd | Low | Critical | defect only happens under certain conditions, parameters unlikey to occurr
| 4th | High | Major | order does not clear after being completed
| 5th | Medium | Major | items from placed order can't be read fully (cut out text).
| 6th | Low | Major | order items don't show price cents
| 7th | High | Minor | spelling error on product logo
| 8th | Medium | Minor | color of a item does not match others. likely to encounter, does not affect functionality.
| 9th | Low | Minor | spelling error in the about section. very unlikely to encounter.
|===

== References

* [1] Madhuri Hammad, "Defect Management Process". July 15, 2025. [Online]. Accessed: February 12, 2026. Available at: https://www.geeksforgeeks.org/software-engineering/defect-management-process/

* [2] TestKarts, "Severity and Priority of Defects Tutorial". [Online]. Accessed: February 12, 2026. Available at: https://www.testkarts.com/manual-testing/severity-and-priority-of-defects#how-to-determine-severity-and-priority

* [3] TestingFrameworks UK, "The Defect Life Cycle in Software Testing: Understanding Stages and Significance" November 12, 2024. [Online]. Accessed: February 13, 2026. Available at: https://www.linkedin.com/pulse/defect-life-cycle-software-testing-understanding-stages-8l0gc

* [4] Vijay, "Defect Severity and Priority in Testing with High Severity and Low Priority Example" May 9,2025. [Online]. Accessed: February 14, 2026. Available at: https://www.softwaretestinghelp.com/how-to-set-defect-priority-and-severity-with-defect-triage-process/

