name: "auto-test suite"

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main]    
jobs:

    build-and-lint:
        runs-on: ubuntu-latest
        steps:
        - name: Check-out repo
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
        - name: install dependencies
          run: npm install
        - name: Compile TypeScript CI scripts
          run: npm run build:tests
        - name: Auto Test Suite
          run: npm run ci-check
          env:
            EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
            EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
            





